server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka #http://localhost:8761/eureka
    enabled: true

spring:
  application:
    name: movies-service
  data:
    mongodb:
      uri: mongodb://mongo-db:27017/moviesdb   #mongodb://localhost:27017/moviesdb    
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/digitalmedia  #http://localhost:8082/realms/digitalmedia
        registration:
          client-id: microservicios
          client-secret: aBwfFDD7MYhE7s2enfwwyfpQSSps7j14
          redirect-uri: http://localhost:8080/*
          scope: openid
app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

