spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: http://localhost:8087
          predicates:
            - Path=/users/**
        - id: movies-service
          uri: http://localhost:8086
          predicates:
            - Path=/movies/**
        - id: facturacion-service
          uri: http://localhost:8088
          predicates:
            - Path=/bills/**
    security:
      oauth2:
        client:
          provider:
            api-gateway:
              issuer-uri: http://localhost:8082/realms/digitalmedia
              jwk-set-uri: http://localhost:8082/realms/digitalmedia/protocol/openid-connect/certs
          registration:
            api-gateway:
              client-id: api-gateway
              client-secret: LUiocaQLZMjxoykgug68zL4S2gt5XAu4
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
              scope: openid
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8080

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway